### ISSUE TITLE
Some promise support

### ISSUE THREAD

**Issue by TrySound** [jonschlinkert/dest#3]
Hi!
There is a problem. Need to use custom dest to add uglify. bundle.write do not support hook after generating, so I want to generate, transform and write by this.
https://github.com/TrySound/case/blob/3.0/gulpfile.js#L49-L56

[Here's api](https://github.com/rollup/rollup/wiki/JavaScript-API)

Which promise support did you want?

**Comment by TrySound** [comment]
Maybe something like this?

``` js
gulp.task(function () {
  var file = {path: 'some path', contents: Buffer or string}
  // returns promise by default caz it more useful
  return dest(file or file llke object, dest folder, options);
});
```

and

``` js
gulp.task(function () {
  return gulp.src(some paths)
    .pipe(dest(dest folder, {stream: true}));
});
```

**Comment by jonschlinkert** [comment]
Hey just noticed you closed this, sorry for not replying. I remember typing a response to this issue, so it's strange, I must not have clicked the comment button or something.

**Comment by TrySound** [comment]
@jonschlinkert It's not relevant now. Let's focus on other projects.
